### PR TITLE
#155550063 Create UI designs 

### PR DESCRIPTION
**Pull request by miritih**
#### What does this PR do?
Create HTML templates/designs for WeConnect app front end.
#### Description of Task to be completed?
The following pages have been designed 
 - Landing page/ Business catalog page. Lists all registered businesses 
 - User login page
 - User sign up page
 - Business profile/reviews page 
 - Business registration page
 - Business edit page
#### How should this be manually tested?
Clone this repo, `cd` into `designs/UI` folder. Run `index.html` file 
#### Any background context you want to provide?
The designs are purely built using `Bootstrap4` CSS framework.
#### What are the relevant pivotal tracker stories?
 #155550063
#### Screenshots
catelog
profile
edit_business
login
signup

### CODE REVIEW

**Comment by migot01** [comment]
-Nice choice of color
-good concept of  design
-Why do you have a search bar on all your pages?

**Comment by miritih** [comment]
@migot01  I chose to have a search bar on most pages to make it easer for authenticated users to filter. Users do not not to navigate to one specific page to perform a filter

**Review by xcixor — APPROVED** [review]
Looks good to me, I like the way you use cdns instead of the alternative method, ensures consistent and fast delivery of your site's content.

**Comment by dmkitui** [comment]
Good work, the project is set up according to best practices. A few pointers:

**Kudos on:**
1. Commit messages are consistently informative and follow best practice. 
2. UI/UX is bold and functionally superior. Some of the bold decision like having *search* on every page is a user experience booster.
3. The PR itself is of good quality and ensures any reader can get the app running.

**Take Note of the following**: 
1. Your **ReadMe** is _below expectations_. Edit to include information necessary to test the application and run it to demonstrate the functionality so far.
2. As this is a majorly UI/front-end task, the final designs are important in the PR. Either include screenshots of the outputs or provide a link to where they exist e.g PT.

**Pull request merged**
